travis:
  secure:
    BINSTAR_TOKEN: g3h2TwE3nK+7kmrG/0kWcLZs7jtu3O+/fFdxB7ZIAbJF4NbLCA5r07vXmfryvZKNPSqyBl6f5+1uwxY4ySNv3tGcZ/sKygQjnJ4MiSxFgOtwIMqXED93ngUMI3Af9OIau5lcuytyFEDI7LDyBLJpoDlb1pgq0SV96pdfeAmdtk1hgfd9cmXg83gN5/WvOvOWk1NZggQUdve25fn2FZEMxgEvjFR1Alcn5zQvatZQfxpWDyP0aGf0p7lWFY0FfBYJhD969cWIlu7pysHj1nV92e1wxE8pe0q44xAQLZ/ZUYj62N/VtL5Fd3czxAROdwv+8euSQz12TktfeqK4REgPLUU34miqgQpz10tLf6+Fq0ReYrTKknKKzKOy2YOtIw6UQ3LqDDAfp6yrqztDl5aA6TUh+aJAsCjSQ8Wa4QnVe7hcgLFFW5q9nx91pVyBewpPaMNlG1FdZLlXP2wMuQfYFL2jBQC3fGSPKImZofi77sMvsK7LiSDDGYhjqq+mOesRMNEF4eTkAVfPgUOdMzBVEk8w1fV3KJD0y1T2xPlnFE09brT7AZNO65JXbSa8NV63BxmQGFNSq4iWY1apH8dQc9w/ScoAVM7ot81zLXUvbWCv4NaG55r4Sm0WV+Q8ONA7smNJvBf0/nUE6xSmbRouphQ6BAL4K7Sdq524nVxe8DI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
