travis:
  secure:
    BINSTAR_TOKEN: V1mvAwdTJXkAG2VRlDVaMQivBvaUc2NNfKSWpkfk66p3gTJBQK2QfLQke1piurhb4mtyoygdqYbXcrZc9hvVsAyfsimJgdWs9ar75IuFDhD/G/1fYsjFQ4wxdVGxdW/9peh9YprV9IGjQ2qPUNor7AIwowWU4BGxNGZ8FQQN+hFzXqLFHzUyfN1cQNSnD9CnKxICX6IumvhCOqmcgK0IkVc+Su4gBqTE9EqEY9Ih4Ls0MtGXVjASUbwYwSLIZjt0asBX7qL5Jo55T3yDT7W/WTsLdLIRkOYcML9nNOxYYi/x31dRtwlU9txwASVUAvayHsowWiY6dclOmShh6ugtwGAUZQ2jUrYiCMvE4vesDnVrLRcpKMDxnDVaTncesjlzO8vLnP/k+YKL1L0vlXlbifAVRTrh+3JhKCPsbvuJQmmfOygFuSBElzmNOQB1qC+e4F1swBwjaZDcOOjYSkm4nKNDJfg8rDBJY2jsjlMF8JCuI1VEFE4dcz5s0GUzsflhTUTBnW+sXbGOaHOr8kqY22JcjcdHb4fOqW/WJinNr66M+rPw+gHpd6Fok7zCBxtYyBPCKE1nanirmJOQ2Omao5dZons0dAet62AS7P/QU/AHw9X2NWDoX+SE9atWJVYwut4Jvp0irgH/XuWjgzP1xFLt/Ef2K72z+8rUmD/c/gM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
